name: SonarCloud Analysis (Git Flow)

on:
  push:
    branches: 
      - develop      # Continuous integration branch
      - main         # Production branch
      - 'release/**' # Release branches
      - 'hotfix/**'  # Hotfix branches
  pull_request:
    branches: 
      - develop      # All PRs target develop
      - main         # Release PRs from develop to main
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better analysis
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests with coverage
        run: npm test -- --coverage --coverageReporters=lcov
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      # Strict quality gate for main branch
      - name: Check Quality Gate (main branch only)
        if: github.ref == 'refs/heads/main' || github.base_ref == 'main'
        run: |
          echo "Checking strict quality gates for production..."
          # Add stricter checks for main branch if needed